[package]
name = "puzzle35"
version = "0.1.0"
authors = ["Melissa <77photon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mexprp = "0.3.0"
